# Basic
title: 杨振林的博客
subtitle: 游戏开发者
welcome_message: <a href="https://github.com/zhenlinyang" target="_blank">View on Github</a>
description: 大家好，我是杨振林，一位 iOS / Android / Unity 开发者，希望和大家多多交流。
creator: <a href="http://blog.yangzhenlin.com">Zhenlin Yang</a>

url: "http://blog.yangzhenlin.com"

permalink: /:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Blog

# Navigation buttons in the front page.
nav:
    - {title: 微博, description: Weibo, url: 'http://weibo.com/lz0807fl'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 

# Social
social:
    weibo: lz0807fl
    github: zhenlinyang
    twitter: lz0807fl
    gplus: 107794230303599300657
    mail: mail@yangzhenlin.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
