# Basic
title: Zhenlin Yang's Blog
subtitle: A Mobile Game Developer
welcome_message: <a href="https://github.com/zhenlinyang" target="_blank">Visit My Github</a>
description: Welcome to My Blog
creator: <a href="http://github.yangzhenlin.com">Zhenlin Yang</a>

url: "http://github.yangzhenlin.com"

permalink: /:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Weibo, description: My Weibo, url: 'http://weibo.com/lz0807fl'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 

# Social
social:
    weibo: lz0807fl
    github: zhenlinyang
    twitter: lz0807fl
    gplus: 107794230303599300657
    mail: mail@yangzhenlin.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
